name: "Publish npm package"

on:
  push:
    branches:
      - master # Jalankan workflow hanya jika ada push ke branch `main`

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Gunakan versi Node.js sesuai kebutuhan
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build # Sesuaikan jika ada script build di package.json

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
